/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    {
      type: "category",
      label: "Guides",
      link: { type: "doc", id: "guides/index" },
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Vulcan Next",
      link: { type: "doc", id: "vulcan-next/index" },
      items: [{ type: "autogenerated", dirName: "vulcan-next" }],
    },
    {
      type: "category",
      label: "Vulcan Meteor (legacy)",
      link: { type: "doc", id: "vulcan-meteor-legacy/index" },
      items: [{ type: "autogenerated", dirName: "vulcan-meteor-legacy" }],
    },
  ],
  // But you can create a sidebar manually
};

module.exports = sidebars;
