import { VulcanSchema } from "@vulcan/schema";

type FilterFunction = (args: {
  input: any;
  context: any;
  filterArguments: any;
}) => { selector: Object; options: Object };

/**
 * Vulcan model, generated by the createModel function based on a schema and some options
 */
export interface VulcanModel {
  name: string;
  graphql: {
    typeName: string;
    multiTypeName: string; // plural name for the multi resolver
    multiResolverName: string;
    singleResolverName: string;
    defaultFragment: string;
    defaultFragmentName: string;
  };
  //customFilters: Array<{ name: string; filter: FilterFunction }>;
  schema: VulcanSchema;
}
